### ISSUE TITLE
Keybindings to toggle touchpad state

### ISSUE THREAD

**Issue by ayoisaiah** [mkopta/toggle-touchpad#4]
Could you add keybindings to toggle the touchpad on or off? Because I can't find a way to turn it back on when my touchpad is off. Thanks

**Comment by mkopta** [comment]
Good idea. Will look into that.

**Comment by ayoisaiah** [comment]
Cheers man, looking forward to it!

**Comment by mkopta** [comment]
Sorry for huge delay. I decided I don't want to extend the current functionality of `toggle-touchpad` and `toggle-touchscreen`. I don't use them myself anymore and I don't even have means of testing them properly, however I will still maintain them so they would be compatible with latest Gnome.

**Comment by ayoisaiah** [comment]
@mkopta I don't even use GNOME anymore 😄
